#!/bin/sh

pidof i3lock
[ $? -eq 1 ] || exit 1; # exit for none-zero return code

SCREENSHOT=/tmp/screenshot.png

scrot -z -q 1 $SCREENSHOT
convert $SCREENSHOT -filter Gaussian -resize 50% -define filter:sigma=10 -resize 200% $SCREENSHOT
i3lock -i $SCREENSHOT --nofork
