#!/bin/bash

show_ip() {
  ip addr | grep 'enp2s0' -A5 | grep ',UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/'
}

case $BLOCK_BUTTON in
  3) echo $(show_ip) | xclip ;;  # right click
  *) echo $(show_ip)
esac
