#!/bin/sh

export TERMINAL=/usr/bin/terminology
export XDG_CONFIG_HOME=$HOME/.config
export ELECTRON_TRASH=trash-cli

setxkbmap -model abnt2 -layout br -variant abnt2

nohup xautolock -time 10 -locker ~/.lockscreen > /dev/null &
nohup dunst -config $HOME/.dunstrc > /dev/null &
nohup feh --randomize --bg-fill ~/.wallpapers > /dev/null &
_configure_display &

exec $@
